---
title: "Introduction: What to use Nvivo for"
format: html
---

Nvivo is a software program for managing qualitative analysis projects. 

You can start an Nvivo project at any point in the research lifecycle: at the design phase, when you have already collected data, or even later. 

### How can Nvivo help me? and what can't it do? 

As an **analysis tool**, Nvivo can help you: 

- organise complex coding 
- manage your data sources 
- introduces a system of recording your work and coding - rigour and robustness 
- saves you time compared with manual coding
- help you visualize and cross-check data and coding 

But aside from helping to structure your  *analysis*, Nvivo can be really helpful as a **project management tool**, organising your data and other useful information in one place.

You can also use Nvivo to **collaborate** - you can share projects or using cloud functionality to invite others in. 


Using Nvivo will NOT: 

- make your analysis better
- make meaning- you as the researcher do that 
- automatically provide objectivity and clarity, or ensure reproducibility 

Before you start building your Nvivo project, it's worth reflecting on whether you really need it, and what you want to get out of it.  

Nvivo takes time  to set up and use properly. It is also useful for some forms of qualitative analysis more than others: very good for content analysis, but not so great if you intend to use interpretative phenomenological analysis (IPA). 

Convinced you want to try it? Great, read on....

🤔 Now ask yourself the following questions about your project: 

### **The components: What types of data and files do I have?** 

  This could include things like...
  
    - transcripts of interviews/focus groups 
    - field notes 
    - research tools
    - photographs or images 
    - policy documents
    - literature 
    - video/audio 
    
Please bear in mind that adding large files to Nvivo can slow the software down. For that reason we caution against using Nvivo for compiling many PDF articles, for example. Referencing software might be better for managing academic literature. The same goes for video/audio files. 
  
  It is helpful to imagine how these things might be connected in a file hierachy. 
  
### **What are the main units of analysis?** 
  
  These could be individuals you've interviewed, organisations you've studied, communities you've worked in, etc. And you could have nested units at different levels (e.g. individuals nested in communities). 
  
  These units of analysis might later get created as ['cases'](https://help-nv.qsrinternational.com/20/win/Content/cases/cases.html) in the Nvivo project file, which enable you to keep information about that case all in one place.  
  
  For example, a case within a project file might represent an individual, with multiple linked interview transcripts, some fieldnotes, and some metadata telling of their demographics. 
  
  These cases and case structures can evolve as you conduct your research, too. 
  
  
### **What are the characteristics of these units?**
  
  Now consider what characteristics of these units you have measured. For example, for individuals you have interviewed, you might have socioedemographic data recorded (e.g. age, sex, education)
  This would be known as metadata, and might be recorded in a spreadsheet or table. 
  
### **What are the linkages within the project?**

This might be files that are linked within a single case or individual, for example an individual who has 2 sequential interview transcripts. Or, it might be linkages between different individuals or cases who live in the same household. 

### **What are likely to be key topics or themes?**

This may be unknown at this stage, but you might imagine some key/core themes based on yoru research question such as 'trust in institutions' , 'sense of loss', etc. 

These themes might become ['codes'](https://help-nv.qsrinternational.com/12/win/v12.1.115-d3ea61/Content/nodes/codes.htm)  within your Nvivo project. 

