---
title: "Nvivo Project Setup"
---

This page will walk you through the steps of creating a new project. 

We will cover: 

  + how to import and organise files, 
  + how to create [cases](https://help-nv.qsrinternational.com/20/win/Content/cases/cases.html) and [case classifications](https://help-nv.qsrinternational.com/20/win/Content/classifications/about-classifications.html).

**Dataset** 

We will use data from a longitudinal qualitative study called the [Qualitative Election Study of Britain](https://qesb.info/). 

> The QESB is a collaborative effort between researchers from the UWE Bristol, the University of Dundee, and GESIS in Germany. Since our launch in 2010, our aim has been to learn about the thoughts, feelings, and opinions of every day voters, before and after the UK general election. To this end, we hold focus groups and interviews, online and in-person. During this general election period, we want to hear your thoughts on political life in the UK. Whether it’s about the election, political leaders, parties, economic concerns, the NHS, or climate change, we want to hear it all.

Hear a little bit about the study from one of its PIs, Ediza Carvalho, based at the University of Dundee: 
{{< video https://www.youtube.com/embed/k_nc4-uXZLA?si=sXkU6xovXw-_13FG >}}

The data is open access and available from the [UK Data Service](https://beta.ukdataservice.ac.uk/datacatalogue/studies/?Search=qualitative+election+study+of+britain#!?Search=qualitative%20election%20study%20of%20britain&Page=1&Rows=10&Sort=1&DateFrom=440&DateTo=2025).

We chose this dataset because it contains a variety of file formats, including focus group discussions and in-depth interviews conducted around elections and referenda which are related over time in 2010, 2014, 2015, 2016, and 2017. The data we will be working with is mainly connected to the 2015 and 2016 rounds. 

For more information on open research and data:

  + The [FAIR principles](https://www.go-fair.org/fair-principles/) to improve the findability, accessibility, interoperability, and reuse of digital assets.

  + UK Data Service hub for [archiving qualitative data and secondary analysis](https://ukdataservice.ac.uk/learning-hub/qualitative-data/).

  + UK Data Service hub for [data skills modules](https://ukdataservice.ac.uk/learning-hub/data-skills-modules/), covering research data management, data for reuse, and more.


**Which Nvivo version?** 

This page uses screenshots from [NVivo Windows Release 1  ](https://help-nv.qsrinternational.com/20/win/Content/welcome.htm) (windows and mac versions are shown). Things may look a little different if you’re working on other versions. Differences with versions 14 and 15 are minimal. 

See our cheatsheet for a quick guide to how things differ across versions.  
For more complex tasks, we recommend you consult manuals which are relevant to the version you are working in, which can be found in the [Resources] (resources.qmd) tab above. 

# Downloading the project files

Download and save the project files from the [SGSSS Social group page for Nvivo training](https://social.sgsss.ac.uk/groups/nvivo-training-2024-25/documents/). 

Navigate to documents->2.Data and Project files 





