---
title: "Summary"
---

## Summary

These examples show different ways you can iteratively build upon your project structure as your analysis progresses.

- Your initial structure (folders, codes, cases) can be used to create dynamic sets or query for specific coded sections.
- It is possible to add layers upon layers. A dynamic set can be used as part of a query - saving you having to repeat the specific criteria for it again and again.

It can be useful then, in addition to considering your 'foundational' structure to think about which dynamic sets can add a supporting additional layer to make other tasks easier in the long-term.

It can feel slow and clunky at first getting to grips with creating them, but as you create more your pace will quicken, and through combining them with queries start to more intuitively combine NVivo features in relation to questions that arise during analysis.

---

::: {.callout-important}
## Don't panic!

It is not a problem if you have already started your analysis and not added some of the ways to structure a project file covered in this session.

1. Most - such as auto-coding and creating folders - can be created at any stage.
2. Not every project and analysis needs to use all of these structuring options. Some options also add equivalent structure in different ways, where there is some 'aesthetic choice' in which to use.
3. If your transcripts do not make use of headers to structure the main topics covered, you can still do manual 'broad-brush' coding. (If having this topic-level coding would benefit your analysis!)

Importantly, for some project structure decisions there is no 100% right/wrong way to do it.

In the example covered we had a 'Participants' case folder, containing the cases for all participants, and used a dynamic set to get 'Interview Participants'.

Another project structure may have case folders for 'Interview participants' and 'Focus Group participants, and use a dynamic set to get 'All Participants'.

Note, this would be feasible as long as the interview and focus group participants are two distinct groups. If some participants took part in both interviews and focus groups, then it would not be possible to have separate Cases folders for them, and the project would need to be structured similar to this example.
:::
