---
title: "Synthesis, Intrepretation, and Themes"
---

::: consider

Within qualitative analysis you'll often hear terms like 'synthesis', 'interpretation', and 'themes'. At times this can vague and unhelpful, such as the over-used phrase claiming 'themes emerge' through analysis, without specifying precisely how.

We have though already covered some of the ways through which your analysis develops beyond the simple coding of text:

- Organising your coding within a code hierarchy, identifying broader parent codes and more specific child codes.
- Memos for exploring initial reflections and interpretation.
- Static sets and queries for exploring and refining your coding as your analysis develops.

Another useful feature for building synthesis, interpetation, and themes is framework matrices.

:::

::: zombie

Originally, in pen and paper days, framework matrices were seen as an alternative to thematic coding, where instead of going through transcripts coding text, a matrix is created with rows for each participant and columns for the themes. Information is then summarised for each participant under each columns, aiding in the identifcation of patterns and comparisons.

Within NVivo this is no longer an 'either/or' and 'both' is a perfectly valid option. Importantly, NVivo makes it possible to create a workflow for moving from coding to framework matrices. Indeed, even when adopting a primarly thematic coding approach, it can remain useful to incorporate even a simple framework matrix as a way to further organise and reflect on your initial coding - aiding in developing your analysis further and recording initial summarisation and reflections that help in moving from coding and analysis to writing up.

:::


